### PR TITLE
Search component on homepage

### PR DESCRIPTION
**Pull request by willhausman**
First pass working prototype of a search component on the homepage.

This is my first foray into VueJS. I'm open to critique.  The actual CSS needs help, but doesn't look absolutely atrocious.

Take note of my use of the stripText util. I would like to alter the other filters to do this same matching, as it is more robust than comparing just name and file id.

### CODE REVIEW

**Comment by RaphaelDDL** [comment]
I'll check out the branch and play a bit with it and give you feedback :)

**Comment by RaphaelDDL** [comment]
I liked. 

I understand the aim you said for the trimmed, so we don't need to do conversion on each model change, makes sense.

I checked it out and made a few changes regarding the loading which you added the isLoading but not using on the template, as well as the css (reused `filter-by-name` class with a few overrides.

~~I need to see how I can incorporate my commit on this PR lol, I never did that before on github.. Or I can approve this one then apply mine on top lol.~~

edit:
Also, you did a great job using the store dispatch, so it used the store and kept the data when accessing the other pages. Same by keeping promise all, so if someone directly entered a hero list, then go to home, it'll only trigger the artifact call. 

*clicks tongue* noice!



I'll merge this then create a PR with my changes so you can see and comment on my changes.

**Comment by willhausman** [comment]
I added you as a collaborator to my fork, but you had already merged and made a new PR. Ha!

**Comment by RaphaelDDL** [comment]
#huehue
So, yeah, I was reading this now https://help.github.com/en/articles/committing-changes-to-a-pull-request-branch-created-from-a-fork

Seems you needed to give me permission, which you did after I merged. Doh, sorry. 

_My power level too high, I'm too fast, you couldn't see my movements (insert over 9000 meme here)_

**Pull request merged**
